version: "3.1"

language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer

  # Pretrained embeddings to boost entity and intent detection
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

- name: DIETClassifier
  epochs: 100
  constrain_similarities: true

- name: EntitySynonymMapper

  # For extracting dates, times, etc.
- name: DucklingEntityExtractor
  url: http://localhost:8000
  dimensions:
  - time
  - date
  locale: en_US
  timezone: UTC

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20250812-150456-simple-stool
